#!/usr/bin/env bash

if [ "$EUID" -ne 0 ]
  then echo "Please run as root"
  exit
fi

# Do something very clever. Or really crazy.
# determining which is left as an exercise to the reader.
p="$(dirname $(readlink -f $(which sentinelctl)))/../../../"
cp -r $p/opt/* /opt/
cp -r $p/cfg/* /opt/sentinelone/configuration/

# Might as well restart s1 while we're here.
systemctl restart sentinel-one